### ISSUE TITLE
Add spacing helper classes

### ISSUE THREAD

**Issue by AlexSkrypnyk** [civictheme/uikit#554]
### User story

As a developer
I want have access to spacing helper classes
So that I could adjust the spacing around elements

### Description

Create $spacing map and provide responsive `p*` and `m*` classes as [other](https://getbootstrap.com/docs/5.2/utilities/spacing/#notation) frameworks do.

## Examples

```scss
.mt-0 {
  margin-top: 0 !important;
}

.ms-1 {
  margin-left: ($spacer * .25) !important;
}

.px-2 {
  padding-left: ($spacer * .5) !important;
  padding-right: ($spacer * .5) !important;
}

.p-3 {
  padding: $spacer !important;
}
```

### Acceptance criteria

Given I am a developer
When I add a `p-3` spacing helper class to an element
Then I should see a padding around an element with a value specified in the $spacer map

Given I am a developer
When I add a `m-3` spacing helper class to an element
Then I should see a margin around an element with a value specified in the $spacer map

Given I am a developer
When I add a `m-l-3` spacing helper class to an element
Then I should see a margin around an element with a value specified in the $spacer map **only applied to large breakpoint and up**

**Comment by alan-cole** [comment]
Originally I wanted this option as well, but I'm starting to consider whether there are better options available.

It makes it easy to apply spacing as a dev, particularly when you're working with existing components in new situations, and don't want to extend a component or add a new CSS selector just to add some space.

However, rather than applying to each element we want to space apart, what if we provide a base component that allowed spacing it's children (using `flex` and `gap`). This would mean spacing between elements is set without requiring each child to explicitly set it's margin. It also avoids cases of unwanted space if elements are removed.

I have implemented something like the above as part of an [experience builder preview of CivicTheme](https://github.com/civictheme/civictheme_xb_preview/tree/main/themes/civictheme_xb/components/00-base/flexible-grid) called flexible grid. This allows an XB user a UI to configure up a flex container for laying out items.

There's a number of cases in CivicTheme (like sidebars in `ct-layout`) where it makes sense to space the elements by default, that may remove need for spacing helper classes.

But let's assume we still want spacing helper classes, I think we should consider the following:

- I think this should not be a featured used in the core UI Kit components. Right now the semantic use of classes in UI Kit components would allow those classes to be easily applied elsewhere (e.g in React/Vue components). Introducing more utility classes into components instead of applying spacing in CSS to existing classes would make the update process more fiddly.

- It's common for spacing to change between desktop and mobile. Implementing breakpoints seems like a sensible option.

- I think we should be prefixing all civictheme classes with `.ct-` to avoid accidental style bleed. So we should ensure our helper classes follow the same. We also need to look at fixing the unscoped styles in grid.scss as well.

- We have something similar with `ct-vertical-spacing`. We could extend that, or replace it. 

Here's a basic mockup of what the proposed change could look like:

```scss
// Utility classes for margin and padding
// Format: .ct-[m|p][x|y]?-[1-5]-[breakpoint]
// Examples:
// .ct-m-3-m (margin: ct-spacing(3) at medium breakpoint)
// .ct-px-5-l (padding-left/right: ct-spacing(5) at large breakpoint)
// .ct-my-2-xs (margin-top/bottom: ct-spacing(2) at extra-small breakpoint)

// Define spacing values to generate (1-5)
$spacing-values: (1, 2, 3, 4, 5);

// Conditional breakpoint mixin - only applies media query if not xxs
@mixin ct-conditional-breakpoint($breakpoint) {
  @if $breakpoint == 'xxs' {
    @content;
  } @else {
    @include ct-breakpoint($breakpoint) {
      @content;
    }
  }
}

// Generate utility classes for each spacing value and breakpoint
@each $spacing in $spacing-values {
  @each $breakpoint, $breakpoint-value in $ct-breakpoints {
    // For xxs breakpoint, use empty string (no breakpoint suffix)
    // For other breakpoints, append the breakpoint name
    $breakpoint-suffix: if($breakpoint == 'xxs', '', '-#{$breakpoint}');

    // Margin utilities
    .ct-m-#{$spacing}#{$breakpoint-suffix} {
      @include ct-conditional-breakpoint($breakpoint) {
        margin: ct-spacing($spacing) !important;
      }
    }

    .ct-mx-#{$spacing}#{$breakpoint-suffix} {
      @include ct-conditional-breakpoint($breakpoint) {
        margin-left: ct-spacing($spacing) !important;
        margin-right: ct-spacing($spacing) !important;
      }
    }

    .ct-my-#{$spacing}#{$breakpoint-suffix} {
      @include ct-conditional-breakpoint($breakpoint) {
        margin-top: ct-spacing($spacing) !important;
        margin-bottom: ct-spacing($spacing) !important;
      }
    }

    // Padding utilities
    .ct-p-#{$spacing}#{$breakpoint-suffix} {
      @include ct-conditional-breakpoint($breakpoint) {
        padding: ct-spacing($spacing) !important;
      }
    }

    .ct-px-#{$spacing}#{$breakpoint-suffix} {
      @include ct-conditional-breakpoint($breakpoint) {
        padding-left: ct-spacing($spacing) !important;
        padding-right: ct-spacing($spacing) !important;
      }
    }

    .ct-py-#{$spacing}#{$breakpoint-suffix} {
      @include ct-conditional-breakpoint($breakpoint) {
        padding-top: ct-spacing($spacing) !important;
        padding-bottom: ct-spacing($spacing) !important;
      }
    }
  }
}
```

Given breakpoints `xxs` to `xxl`, this results in about 1400 lines of code. Given the size, if we were to include this feature, we'd probably want to make it optional and bundle it separately to `civictheme.base.css`, maybe as `civictheme.spacing.css` or such.

Or, limit the breakpoints / spacing to only what's most useful? (How do we determine that?)

Happy to hear thoughts, considerations on the above.
